### ISSUE TITLE
Integration hangs on loading screen even after having succesfully set MQTT bridge

### ISSUE THREAD

**Issue by slack1987** [sehaas/ha_hisense_tv#24]
Hi,

After launching the integration setup, and entering the TV MAC Address:
![Pic 1](https://user-images.githubusercontent.com/64207585/153767404-7ce57c84-7598-4788-a66c-724cecbb891f.png)

the TV Shows the 4 digits code, but the integration doesn't move from the following screen:
![Pic 2](https://user-images.githubusercontent.com/64207585/153767427-913c90da-b415-4b7c-8854-c46081fc4161.png)

I tried already to change browser, (I tried Opera, Edge and Chrome) and also the mobile APP.

Any ideas?

**Comment by Saars1337** [comment]
I have the same problem, did you find a solution to this?

**Comment by slack1987** [comment]
I didn't unfortunately, I'm still having the same issue

**Comment by sehaas** [comment]
Unfortunately I can't reproduce your behaviour.

Is your screenshot from before you enter the code or after you submit it?
Have you checked your HA logs for any error?

**Comment by slack1987** [comment]
The screenshot is from before I enter the code, it stops there, I have never been able to enter the code.
I did check HA logs and unfortunately I can't find any related error.

**Comment by Tabisch** [comment]
i dont know if i have the same issue but it looks kinda similar.
i enter all the required information an press the create button and than it hangs at the spinning animation.

i'm running home assistant on docker and have my mqtt server in a another docker container.
my guess is, that the integration tries to create the mqtt bridge which fails, because it doesnt have the ability to change the mqtt server.

it seems that i got the mqtt brigde going with manual config (atleast mosquitto said, it created a connection), but home assistant didnt discover the tv like im familiar which normally happens when i use other integrations.
maybe it just doesnt do that.

tbh i'm just guessing here because neiter familiar with the structure of home assistant integrations nor python as a language.

if the "integration doesnt have ability to change mqtt server" theory is correct, than maybe a viable workaround for that could be, that the integration asks for all the information it does now, than it trys to create bridge and if it fails, it will print out the bridge config for mosquitto, so it can be added manually and the mosquitto docker be restared.
when the mqtt bridge is working, there shouldnt be anything stopping the integration from proceeding the configuration as normal.

**Comment by sehaas** [comment]
No, the integration does not modify and cannot create the MQTT bridge nor the broker. You have to set up the bridge yourself. Your Docker setup shouldn't be a problem. My setup is similar.
Auto-discover isn't implemented - if someone has experience with that I would appreciate support. 

Do you see messages from your TV under the configured prefix on your mosquitto broker?

**Comment by Tabisch** [comment]
I got it running now.
Sorry for bothering you.
No clue, what the hell it was thinking before, when i tried setting this up.

Awesome stuff you are doing, really made my day :).

**Comment by slack1987** [comment]
I finally have it working, It was a browser problem, I was using Opera, I tried to set it up using Chrome and it worked at the first attempt.

Thank you @sehaas for all.
