### ISSUE TITLE
WOL issues

### ISSUE THREAD

**Issue by spilote** [sehaas/ha_hisense_tv#27]
Hey guys, 

I feel like I completed the hardest part of this venture. I successfully configured the MQTT. I have multiple Hisense TV and they all behave the same with WOL. 

I recently purchase a VIDAA version and enable the WOL on both lan and wifi. the WOL is simply not constant. Sometime it works, sometime it doesn't.

I created a script to run  

@echo OFF
FOR /L %%y IN (0, 1, 30000) DO WolCmd.exe MAC (All lowercase, no space) 192.168.1.0 255.255.255.0
PAUSE

Most of the time, when script is completed, the TV is on but it can take minutes before the TV actually turns on.

Any advise? for all my other Hisense TV, I simply run that command once and it works... not sure where to go from here.

Thansk.

**Comment by sehaas** [comment]
Not sure what could cause the difference. But maybe you could check `Settings -> System -> Advanced Settings -> Fast Power Mode`

**Comment by spilote** [comment]
Yeah, tried that, on or off, same behavior. Thanks tho.

**Comment by n0ahk** [comment]
I changed the Wake On LAN command to only use the MAC address, which made Wake On LAN on the TV much more stable.
![image](https://user-images.githubusercontent.com/71713670/164466018-8ed90f3a-6ad9-410a-995c-e8113393696b.png)

**Comment by ghost** [comment]
Funny behavior and no idea where it's coming from.
I have a HiSense A71 series which costed me many hours to finally get WoL to work. I am not 100% certain where the issue is coming from. I suspect this is because the TV doesn't have an actual 'network standby' mode, like my AV receiver does (when the TV is off, it's really off - IP address not pingable; when the receiver is off, it's still pingable).
To complicate matters more, my TV is / was in a separate VLAN than the HA box. Routing etc was fine - connectivity was trouble-free once I started the TV manually. Using latest across the board (TV firmware, HA version, HiSense integration) and completed all information (MAC address, IP address etc) in the integration configuration.

Symptom 1: wake from HA GUI (using the hisense integration on/off switch) doesn't work. 
Symptom 2: 'wakeonlan' command-line client from the HA machine (Ubuntu) doesn't work; 'etherwake' from the same machine however worked fine (before that, I suspected the TV was somewhat broken)

Suspected cause: missing ARP entry for the HiSense TV (it disappears about 30 seconds after the TV is shut down)
Workaround: created a network interface in the same VLAN, then created the ARP entry manually ("arp -s <IP address> <MAC address>"); WoL from HA will work fine. The first step alone (extra network interface) didn't help.

Curious if anyone has further insight into this. I am moderately competent with IT, but I am not a network expert.
